### ISSUE TITLE
File import not working

### ISSUE THREAD

**Issue by dsrezoon** [bsondermann/Blackbox2Sound#1]
I am importing a Betaflight Log via Drag&Drop. Somehow Blackbox2Sound creates one .csv file in the Filesystem but nothing else happens and it is not importing the File.

Tried with multiple Files on latest Windows 10

**Comment by bsondermann** [comment]
Hi, do you use .BFL or .bbl logs?

**Comment by dsrezoon** [comment]
i am trying .bbl logs

**Comment by bsondermann** [comment]
ah ok, .bbl logs are currently not really supported. I dont know why it worked in the uav tech video xD.
I will add support in the next update. maybe i can do it today.

**Comment by dsrezoon** [comment]
this would really be great. Thank you!

**Comment by bsondermann** [comment]
I just released a new update. For me it worked, but please test it and let me know whether it worked for you too. 
Stay safe!

**Comment by dsrezoon** [comment]
works great! thank you!
