### ISSUE TITLE
Log remains "loading" indefinitely

### ISSUE THREAD

**Issue by jelehmann** [bsondermann/Blackbox2Sound#3]
1. extracted Blackbox2Sound V1.3 completely to new directory
2. run Blackbox2Sound.exe (Microsoft Windows 10 Home, Version 10.0.18363 Build 18363)
3. "NO FILE LOADED!" visible
4. drag and drop "btfl_all.bbl" into Blackbox2Sound Window (see attached file)
5. "LOADING FILE...!" apperars in Blackbox2Sound Window
6. .\temp\0\csv\btfl_all.01.csv to btfl_all.05.csv are generated
7. nothing else happens. "LOADING FILE...!" stays visible in Blackbox2Sound Window

[2020.09.27 Alpha A85.zip](https://github.com/bsondermann/Blackbox2Sound/files/5422225/2020.09.27.Alpha.A85.zip)

Is a Blackbox2Sound logfile generated anywhere?

**Comment by bsondermann** [comment]
I will take a look asap!

**Comment by bsondermann** [comment]
I think I fixed it. Please give it a try :D
Stay safe!

**Comment by jelehmann** [comment]
fixed! :-)
